INSERT INTO users (id, username, password, email) VALUES
       ('eef8c718-b25e-11e9-a2a3-2a2ae2dbcce4','vas','a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3','vas.vas@vas.com');
insert into job_applications (id, sector, profession, salary, description) values ('38ed1a93-6abb-47c0-bfd0-ffbccc96b757', 'SECURITY', 'Physician', 5060.3, 'ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec');
insert into job_applications (id, sector, profession, salary, description) values ('8b9d884b-ccdd-47a5-a894-e14b0529b9d5', 'MEDICINE', 'Database administrator', 4232.81, 'nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien');
insert into job_applications (id, sector, profession, salary, description) values ('dd148c94-97fe-4457-bdb8-2ccc591a80f2', 'FOOD', 'Database administrator', 3816.43, 'sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis');
insert into job_applications (id, sector, profession, salary, description) values ('574ad937-9ff7-4afa-abcc-e2122f27ee90', 'CAR', 'Social Worker', 8659.84, 'turpis enim blandit mi in porttitor pede justo eu massa donec dapibus duis');
insert into job_applications (id, sector, profession, salary, description) values ('79d2680d-7402-4909-8615-bd712ba3da06', 'MEDICINE', 'Hairdresser', 4296.5, 'tellus nisi eu orci mauris lacinia sapien quis libero nullam');
insert into job_applications (id, sector, profession, salary, description) values ('99d97d3c-ba48-433b-9bf6-39fff5827cd0', 'FOOD', 'Medical Assistant', 6988.15, 'sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus');
insert into job_applications (id, sector, profession, salary, description) values ('267453b3-a071-46ff-8075-b6e7d8eacb0f', 'DOMESTIC', 'Sports Coach', 2109.48, 'orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus');
insert into job_applications (id, sector, profession, salary, description) values ('ebdea35b-a521-49ba-bc4d-762efe2527ce', 'FOOD', 'Medical Assistant', 7528.0, 'ullamcorper purus sit amet nulla quisque arcu libero rutrum ac lobortis vel dapibus');
insert into job_applications (id, sector, profession, salary, description) values ('1c6c4ca5-b513-40a3-a3ec-d217b4e16348', 'SECURITY', 'Childcare worker', 3244.52, 'nec sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy');
insert into job_applications (id, sector, profession, salary, description) values ('92d145e7-cc8e-4458-9afc-fb6b1af0530f', 'MEDICINE', 'Physician', 5442.56, 'est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien');
